version: '3.7'

services:
  database_crossapp:
    image: postgres
    container_name: database_crossapp
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=crossapp
      - POSTGRES_DB=crossapp_db
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: crossapp_api
    ports: 
      - 3000:3000
    volumes:
      - .:/usr/app
    network_mode: host

volumes: 
  pgdata:
    driver: local